// Code generated by entc, DO NOT EDIT.

package dobuckets

import (
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/pepeunlimited/files/internal/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.DoBuckets {
	return predicate.DoBuckets(
		func(s *sql.Selector) {
			s.Where(sql.EQ(s.C(FieldID), id))
		},
	)
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	},
	)
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	},
	)
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	},
	)
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	},
	)
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	},
	)
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	},
	)
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	},
	)
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	},
	)
}

// BucketName applies equality check predicate on the "bucket_name" field. It's identical to BucketNameEQ.
func BucketName(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldBucketName), v))
	},
	)
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEndpoint), v))
	},
	)
}

// CdnEndpoint applies equality check predicate on the "cdn_endpoint" field. It's identical to CdnEndpointEQ.
func CdnEndpoint(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCdnEndpoint), v))
	},
	)
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	},
	)
}

// BucketNameEQ applies the EQ predicate on the "bucket_name" field.
func BucketNameEQ(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldBucketName), v))
	},
	)
}

// BucketNameNEQ applies the NEQ predicate on the "bucket_name" field.
func BucketNameNEQ(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldBucketName), v))
	},
	)
}

// BucketNameIn applies the In predicate on the "bucket_name" field.
func BucketNameIn(vs ...string) predicate.DoBuckets {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.DoBuckets(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldBucketName), v...))
	},
	)
}

// BucketNameNotIn applies the NotIn predicate on the "bucket_name" field.
func BucketNameNotIn(vs ...string) predicate.DoBuckets {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.DoBuckets(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldBucketName), v...))
	},
	)
}

// BucketNameGT applies the GT predicate on the "bucket_name" field.
func BucketNameGT(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldBucketName), v))
	},
	)
}

// BucketNameGTE applies the GTE predicate on the "bucket_name" field.
func BucketNameGTE(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldBucketName), v))
	},
	)
}

// BucketNameLT applies the LT predicate on the "bucket_name" field.
func BucketNameLT(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldBucketName), v))
	},
	)
}

// BucketNameLTE applies the LTE predicate on the "bucket_name" field.
func BucketNameLTE(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldBucketName), v))
	},
	)
}

// BucketNameContains applies the Contains predicate on the "bucket_name" field.
func BucketNameContains(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldBucketName), v))
	},
	)
}

// BucketNameHasPrefix applies the HasPrefix predicate on the "bucket_name" field.
func BucketNameHasPrefix(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldBucketName), v))
	},
	)
}

// BucketNameHasSuffix applies the HasSuffix predicate on the "bucket_name" field.
func BucketNameHasSuffix(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldBucketName), v))
	},
	)
}

// BucketNameEqualFold applies the EqualFold predicate on the "bucket_name" field.
func BucketNameEqualFold(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldBucketName), v))
	},
	)
}

// BucketNameContainsFold applies the ContainsFold predicate on the "bucket_name" field.
func BucketNameContainsFold(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldBucketName), v))
	},
	)
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEndpoint), v))
	},
	)
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldEndpoint), v))
	},
	)
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.DoBuckets {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.DoBuckets(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldEndpoint), v...))
	},
	)
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.DoBuckets {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.DoBuckets(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldEndpoint), v...))
	},
	)
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldEndpoint), v))
	},
	)
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldEndpoint), v))
	},
	)
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldEndpoint), v))
	},
	)
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldEndpoint), v))
	},
	)
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldEndpoint), v))
	},
	)
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldEndpoint), v))
	},
	)
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldEndpoint), v))
	},
	)
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldEndpoint), v))
	},
	)
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldEndpoint), v))
	},
	)
}

// CdnEndpointEQ applies the EQ predicate on the "cdn_endpoint" field.
func CdnEndpointEQ(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCdnEndpoint), v))
	},
	)
}

// CdnEndpointNEQ applies the NEQ predicate on the "cdn_endpoint" field.
func CdnEndpointNEQ(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCdnEndpoint), v))
	},
	)
}

// CdnEndpointIn applies the In predicate on the "cdn_endpoint" field.
func CdnEndpointIn(vs ...string) predicate.DoBuckets {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.DoBuckets(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCdnEndpoint), v...))
	},
	)
}

// CdnEndpointNotIn applies the NotIn predicate on the "cdn_endpoint" field.
func CdnEndpointNotIn(vs ...string) predicate.DoBuckets {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.DoBuckets(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCdnEndpoint), v...))
	},
	)
}

// CdnEndpointGT applies the GT predicate on the "cdn_endpoint" field.
func CdnEndpointGT(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCdnEndpoint), v))
	},
	)
}

// CdnEndpointGTE applies the GTE predicate on the "cdn_endpoint" field.
func CdnEndpointGTE(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCdnEndpoint), v))
	},
	)
}

// CdnEndpointLT applies the LT predicate on the "cdn_endpoint" field.
func CdnEndpointLT(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCdnEndpoint), v))
	},
	)
}

// CdnEndpointLTE applies the LTE predicate on the "cdn_endpoint" field.
func CdnEndpointLTE(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCdnEndpoint), v))
	},
	)
}

// CdnEndpointContains applies the Contains predicate on the "cdn_endpoint" field.
func CdnEndpointContains(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldCdnEndpoint), v))
	},
	)
}

// CdnEndpointHasPrefix applies the HasPrefix predicate on the "cdn_endpoint" field.
func CdnEndpointHasPrefix(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldCdnEndpoint), v))
	},
	)
}

// CdnEndpointHasSuffix applies the HasSuffix predicate on the "cdn_endpoint" field.
func CdnEndpointHasSuffix(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldCdnEndpoint), v))
	},
	)
}

// CdnEndpointIsNil applies the IsNil predicate on the "cdn_endpoint" field.
func CdnEndpointIsNil() predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldCdnEndpoint)))
	},
	)
}

// CdnEndpointNotNil applies the NotNil predicate on the "cdn_endpoint" field.
func CdnEndpointNotNil() predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldCdnEndpoint)))
	},
	)
}

// CdnEndpointEqualFold applies the EqualFold predicate on the "cdn_endpoint" field.
func CdnEndpointEqualFold(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldCdnEndpoint), v))
	},
	)
}

// CdnEndpointContainsFold applies the ContainsFold predicate on the "cdn_endpoint" field.
func CdnEndpointContainsFold(v string) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldCdnEndpoint), v))
	},
	)
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	},
	)
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	},
	)
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DoBuckets {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.DoBuckets(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	},
	)
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DoBuckets {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.DoBuckets(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	},
	)
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	},
	)
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	},
	)
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	},
	)
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DoBuckets {
	return predicate.DoBuckets(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	},
	)
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.DoBuckets) predicate.DoBuckets {
	return predicate.DoBuckets(
		func(s *sql.Selector) {
			s1 := s.Clone().SetP(nil)
			for _, p := range predicates {
				p(s1)
			}
			s.Where(s1.P())
		},
	)
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.DoBuckets) predicate.DoBuckets {
	return predicate.DoBuckets(
		func(s *sql.Selector) {
			s1 := s.Clone().SetP(nil)
			for i, p := range predicates {
				if i > 0 {
					s1.Or()
				}
				p(s1)
			}
			s.Where(s1.P())
		},
	)
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DoBuckets) predicate.DoBuckets {
	return predicate.DoBuckets(
		func(s *sql.Selector) {
			p(s.Not())
		},
	)
}
