// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"github.com/pepeunlimited/files/internal/pkg/ent/buckets"
	"github.com/pepeunlimited/files/internal/pkg/ent/files"
	"github.com/pepeunlimited/files/internal/pkg/ent/migrate"
	"log"

	"github.com/facebookincubator/ent/dialect"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Buckets is the client for interacting with the Buckets builders.
	Buckets *BucketsClient
	// Files is the client for interacting with the Files builders.
	Files *FilesClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	c := config{log: log.Println}
	c.options(opts...)
	return &Client{
		config:  c,
		Schema:  migrate.NewSchema(c.driver),
		Buckets: NewBucketsClient(c),
		Files:   NewFilesClient(c),
	}
}

// Open opens a connection to the database specified by the driver name and a
// driver-specific data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: tx, log: c.log, debug: c.debug}
	return &Tx{
		config:  cfg,
		Buckets: NewBucketsClient(cfg),
		Files:   NewFilesClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Buckets.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true}
	return &Client{
		config:  cfg,
		Schema:  migrate.NewSchema(cfg.driver),
		Buckets: NewBucketsClient(cfg),
		Files:   NewFilesClient(cfg),
	}
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// BucketsClient is a client for the Buckets schema.
type BucketsClient struct {
	config
}

// NewBucketsClient returns a client for the Buckets from the given config.
func NewBucketsClient(c config) *BucketsClient {
	return &BucketsClient{config: c}
}

// Create returns a create builder for Buckets.
func (c *BucketsClient) Create() *BucketsCreate {
	return &BucketsCreate{config: c.config}
}

// Update returns an update builder for Buckets.
func (c *BucketsClient) Update() *BucketsUpdate {
	return &BucketsUpdate{config: c.config}
}

// UpdateOne returns an update builder for the given entity.
func (c *BucketsClient) UpdateOne(b *Buckets) *BucketsUpdateOne {
	return c.UpdateOneID(b.ID)
}

// UpdateOneID returns an update builder for the given id.
func (c *BucketsClient) UpdateOneID(id int) *BucketsUpdateOne {
	return &BucketsUpdateOne{config: c.config, id: id}
}

// Delete returns a delete builder for Buckets.
func (c *BucketsClient) Delete() *BucketsDelete {
	return &BucketsDelete{config: c.config}
}

// DeleteOne returns a delete builder for the given entity.
func (c *BucketsClient) DeleteOne(b *Buckets) *BucketsDeleteOne {
	return c.DeleteOneID(b.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *BucketsClient) DeleteOneID(id int) *BucketsDeleteOne {
	return &BucketsDeleteOne{c.Delete().Where(buckets.ID(id))}
}

// Create returns a query builder for Buckets.
func (c *BucketsClient) Query() *BucketsQuery {
	return &BucketsQuery{config: c.config}
}

// Get returns a Buckets entity by its id.
func (c *BucketsClient) Get(ctx context.Context, id int) (*Buckets, error) {
	return c.Query().Where(buckets.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BucketsClient) GetX(ctx context.Context, id int) *Buckets {
	b, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return b
}

// QueryFiles queries the files edge of a Buckets.
func (c *BucketsClient) QueryFiles(b *Buckets) *FilesQuery {
	query := &FilesQuery{config: c.config}
	id := b.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(buckets.Table, buckets.FieldID, id),
		sqlgraph.To(files.Table, files.FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, buckets.FilesTable, buckets.FilesColumn),
	)
	query.sql = sqlgraph.Neighbors(b.driver.Dialect(), step)

	return query
}

// FilesClient is a client for the Files schema.
type FilesClient struct {
	config
}

// NewFilesClient returns a client for the Files from the given config.
func NewFilesClient(c config) *FilesClient {
	return &FilesClient{config: c}
}

// Create returns a create builder for Files.
func (c *FilesClient) Create() *FilesCreate {
	return &FilesCreate{config: c.config}
}

// Update returns an update builder for Files.
func (c *FilesClient) Update() *FilesUpdate {
	return &FilesUpdate{config: c.config}
}

// UpdateOne returns an update builder for the given entity.
func (c *FilesClient) UpdateOne(f *Files) *FilesUpdateOne {
	return c.UpdateOneID(f.ID)
}

// UpdateOneID returns an update builder for the given id.
func (c *FilesClient) UpdateOneID(id int) *FilesUpdateOne {
	return &FilesUpdateOne{config: c.config, id: id}
}

// Delete returns a delete builder for Files.
func (c *FilesClient) Delete() *FilesDelete {
	return &FilesDelete{config: c.config}
}

// DeleteOne returns a delete builder for the given entity.
func (c *FilesClient) DeleteOne(f *Files) *FilesDeleteOne {
	return c.DeleteOneID(f.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *FilesClient) DeleteOneID(id int) *FilesDeleteOne {
	return &FilesDeleteOne{c.Delete().Where(files.ID(id))}
}

// Create returns a query builder for Files.
func (c *FilesClient) Query() *FilesQuery {
	return &FilesQuery{config: c.config}
}

// Get returns a Files entity by its id.
func (c *FilesClient) Get(ctx context.Context, id int) (*Files, error) {
	return c.Query().Where(files.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FilesClient) GetX(ctx context.Context, id int) *Files {
	f, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return f
}

// QueryBuckets queries the buckets edge of a Files.
func (c *FilesClient) QueryBuckets(f *Files) *BucketsQuery {
	query := &BucketsQuery{config: c.config}
	id := f.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(files.Table, files.FieldID, id),
		sqlgraph.To(buckets.Table, buckets.FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, files.BucketsTable, files.BucketsColumn),
	)
	query.sql = sqlgraph.Neighbors(f.driver.Dialect(), step)

	return query
}
