// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateBucketParams struct {
	BucketName           string                `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	Region               string                `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Endpoint             string                `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Location             *wrappers.StringValue `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	IsCdn                bool                  `protobuf:"varint,5,opt,name=is_cdn,json=isCdn,proto3" json:"is_cdn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateBucketParams) Reset()         { *m = CreateBucketParams{} }
func (m *CreateBucketParams) String() string { return proto.CompactTextString(m) }
func (*CreateBucketParams) ProtoMessage()    {}
func (*CreateBucketParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{0}
}

func (m *CreateBucketParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBucketParams.Unmarshal(m, b)
}
func (m *CreateBucketParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBucketParams.Marshal(b, m, deterministic)
}
func (m *CreateBucketParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBucketParams.Merge(m, src)
}
func (m *CreateBucketParams) XXX_Size() int {
	return xxx_messageInfo_CreateBucketParams.Size(m)
}
func (m *CreateBucketParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBucketParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBucketParams proto.InternalMessageInfo

func (m *CreateBucketParams) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *CreateBucketParams) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *CreateBucketParams) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *CreateBucketParams) GetLocation() *wrappers.StringValue {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *CreateBucketParams) GetIsCdn() bool {
	if m != nil {
		return m.IsCdn
	}
	return false
}

type CreateBucketResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBucketResponse) Reset()         { *m = CreateBucketResponse{} }
func (m *CreateBucketResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBucketResponse) ProtoMessage()    {}
func (*CreateBucketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{1}
}

func (m *CreateBucketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBucketResponse.Unmarshal(m, b)
}
func (m *CreateBucketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBucketResponse.Marshal(b, m, deterministic)
}
func (m *CreateBucketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBucketResponse.Merge(m, src)
}
func (m *CreateBucketResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBucketResponse.Size(m)
}
func (m *CreateBucketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBucketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBucketResponse proto.InternalMessageInfo

type CreateFileParams struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	BucketName           string   `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	ContentLength        int64    `protobuf:"varint,3,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	MimeType             string   `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFileParams) Reset()         { *m = CreateFileParams{} }
func (m *CreateFileParams) String() string { return proto.CompactTextString(m) }
func (*CreateFileParams) ProtoMessage()    {}
func (*CreateFileParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{2}
}

func (m *CreateFileParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFileParams.Unmarshal(m, b)
}
func (m *CreateFileParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFileParams.Marshal(b, m, deterministic)
}
func (m *CreateFileParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFileParams.Merge(m, src)
}
func (m *CreateFileParams) XXX_Size() int {
	return xxx_messageInfo_CreateFileParams.Size(m)
}
func (m *CreateFileParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFileParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFileParams proto.InternalMessageInfo

func (m *CreateFileParams) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *CreateFileParams) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *CreateFileParams) GetContentLength() int64 {
	if m != nil {
		return m.ContentLength
	}
	return 0
}

func (m *CreateFileParams) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}

type File struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Id                   int64    `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	ContentLength        int64    `protobuf:"varint,6,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	MimeType             string   `protobuf:"bytes,7,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{3}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *File) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *File) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *File) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *File) GetContentLength() int64 {
	if m != nil {
		return m.ContentLength
	}
	return 0
}

func (m *File) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateBucketParams)(nil), "pepeunlimited.todo.CreateBucketParams")
	proto.RegisterType((*CreateBucketResponse)(nil), "pepeunlimited.todo.CreateBucketResponse")
	proto.RegisterType((*CreateFileParams)(nil), "pepeunlimited.todo.CreateFileParams")
	proto.RegisterType((*File)(nil), "pepeunlimited.todo.File")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_9188e3b7e55e1162) }

var fileDescriptor_9188e3b7e55e1162 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x6f, 0xd4, 0x30,
	0x10, 0xc5, 0xe5, 0xa4, 0x1b, 0x92, 0x59, 0xa8, 0x90, 0x05, 0x55, 0x14, 0xfe, 0xad, 0x22, 0x40,
	0x39, 0xa5, 0x52, 0xb9, 0x70, 0x6d, 0x2b, 0x71, 0xaa, 0x10, 0x4a, 0x11, 0x07, 0x2e, 0xc1, 0x1b,
	0x4f, 0x83, 0x45, 0x62, 0x5b, 0x8e, 0x03, 0xea, 0xe7, 0xe0, 0xab, 0x70, 0x42, 0xe2, 0xbb, 0xa1,
	0x38, 0xd9, 0x25, 0xb4, 0x0b, 0x7b, 0x9c, 0xf7, 0xc6, 0xd1, 0xef, 0xbd, 0x0c, 0xc0, 0x95, 0x68,
	0x30, 0xd7, 0x46, 0x59, 0x45, 0xa9, 0x46, 0x8d, 0xbd, 0x6c, 0x44, 0x2b, 0x2c, 0xf2, 0xdc, 0x2a,
	0xae, 0x92, 0xa7, 0xb5, 0x52, 0x75, 0x83, 0xc7, 0x6e, 0x63, 0xdd, 0x5f, 0x1d, 0x7f, 0x33, 0x4c,
	0x6b, 0x34, 0xdd, 0xf8, 0x26, 0xfd, 0x49, 0x80, 0x9e, 0x1b, 0x64, 0x16, 0xcf, 0xfa, 0xea, 0x0b,
	0xda, 0x77, 0xcc, 0xb0, 0xb6, 0xa3, 0xcf, 0x60, 0xb9, 0x76, 0x73, 0x29, 0x59, 0x8b, 0x31, 0x59,
	0x91, 0x2c, 0x2a, 0x60, 0x94, 0xde, 0xb2, 0x16, 0xe9, 0x11, 0x04, 0x06, 0x6b, 0xa1, 0x64, 0xec,
	0x39, 0x6f, 0x9a, 0x68, 0x02, 0x21, 0x4a, 0xae, 0x95, 0x90, 0x36, 0xf6, 0x9d, 0xb3, 0x9d, 0xe9,
	0x6b, 0x08, 0x1b, 0x55, 0x31, 0x3b, 0xbc, 0x3a, 0x58, 0x91, 0x6c, 0x79, 0xf2, 0x38, 0x1f, 0xf1,
	0xf2, 0x0d, 0x5e, 0x7e, 0x69, 0x8d, 0x90, 0xf5, 0x07, 0xd6, 0xf4, 0x58, 0x6c, 0xb7, 0xe9, 0x43,
	0x08, 0x44, 0x57, 0x56, 0x5c, 0xc6, 0x8b, 0x15, 0xc9, 0xc2, 0x62, 0x21, 0xba, 0x73, 0x2e, 0xd3,
	0x23, 0x78, 0x30, 0x67, 0x2f, 0xb0, 0xd3, 0x4a, 0x76, 0x98, 0x7e, 0x27, 0x70, 0x7f, 0x34, 0xde,
	0x88, 0x06, 0xa7, 0x48, 0x09, 0x84, 0x43, 0x57, 0xb3, 0x3c, 0xdb, 0xf9, 0x66, 0x5c, 0xef, 0x56,
	0xdc, 0x17, 0x70, 0x58, 0x29, 0x69, 0x51, 0xda, 0xb2, 0x41, 0x59, 0xdb, 0xcf, 0x2e, 0x9c, 0x5f,
	0xdc, 0x9b, 0xd4, 0x0b, 0x27, 0xd2, 0x47, 0x10, 0xb5, 0xa2, 0xc5, 0xd2, 0x5e, 0x6b, 0x74, 0x11,
	0xa3, 0x22, 0x1c, 0x84, 0xf7, 0xd7, 0x1a, 0xd3, 0x1f, 0x04, 0x0e, 0x06, 0x9e, 0xff, 0x92, 0x3c,
	0x01, 0xa8, 0x1c, 0x39, 0x2f, 0x99, 0x9d, 0x40, 0xa2, 0x49, 0x39, 0xb5, 0x83, 0xdd, 0x6b, 0xbe,
	0xb1, 0xc7, 0x82, 0xa3, 0x49, 0x39, 0xb5, 0xf4, 0x10, 0x3c, 0xc1, 0x5d, 0x47, 0x7e, 0xe1, 0x09,
	0xbe, 0x03, 0x3b, 0xd8, 0x8b, 0x7d, 0xe7, 0x6f, 0xec, 0x93, 0x5f, 0x04, 0x96, 0x03, 0xf6, 0x25,
	0x9a, 0xaf, 0xa2, 0x42, 0x7a, 0x01, 0xf0, 0xa7, 0x5b, 0xfa, 0x3c, 0xbf, 0x7d, 0x74, 0xf9, 0xcd,
	0xee, 0x93, 0x78, 0xd7, 0x96, 0x7b, 0xff, 0x09, 0xee, 0xce, 0x7f, 0x21, 0x7d, 0xf9, 0xef, 0xef,
	0xcd, 0x0f, 0x34, 0xc9, 0xf6, 0xed, 0x6d, 0x8e, 0xe1, 0x6c, 0xf1, 0xd1, 0x37, 0xba, 0x5a, 0x07,
	0xee, 0xc4, 0x5e, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x00, 0xb9, 0x57, 0x4b, 0x31, 0x03, 0x00,
	0x00,
}
