// Code generated by protoc-gen-go. DO NOT EDIT.
// source: image.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateImageParams struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	BucketId             string   `protobuf:"bytes,2,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	ContentLength        int64    `protobuf:"varint,3,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	MimeType             string   `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	ObjectId             string   `protobuf:"bytes,5,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateImageParams) Reset()         { *m = CreateImageParams{} }
func (m *CreateImageParams) String() string { return proto.CompactTextString(m) }
func (*CreateImageParams) ProtoMessage()    {}
func (*CreateImageParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_9624c68e2b547544, []int{0}
}

func (m *CreateImageParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateImageParams.Unmarshal(m, b)
}
func (m *CreateImageParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateImageParams.Marshal(b, m, deterministic)
}
func (m *CreateImageParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateImageParams.Merge(m, src)
}
func (m *CreateImageParams) XXX_Size() int {
	return xxx_messageInfo_CreateImageParams.Size(m)
}
func (m *CreateImageParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateImageParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateImageParams proto.InternalMessageInfo

func (m *CreateImageParams) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *CreateImageParams) GetBucketId() string {
	if m != nil {
		return m.BucketId
	}
	return ""
}

func (m *CreateImageParams) GetContentLength() int64 {
	if m != nil {
		return m.ContentLength
	}
	return 0
}

func (m *CreateImageParams) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}

func (m *CreateImageParams) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

type Image struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsDeleted            bool     `protobuf:"varint,4,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	BucketId             string   `protobuf:"bytes,5,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	Id                   int64    `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	ContentLength        int64    `protobuf:"varint,7,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	MimeType             string   `protobuf:"bytes,8,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	ObjectId             string   `protobuf:"bytes,9,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_9624c68e2b547544, []int{1}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *Image) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Image) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Image) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

func (m *Image) GetBucketId() string {
	if m != nil {
		return m.BucketId
	}
	return ""
}

func (m *Image) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Image) GetContentLength() int64 {
	if m != nil {
		return m.ContentLength
	}
	return 0
}

func (m *Image) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}

func (m *Image) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateImageParams)(nil), "pepeunlimited.todo.CreateImageParams")
	proto.RegisterType((*Image)(nil), "pepeunlimited.todo.Image")
}

func init() { proto.RegisterFile("image.proto", fileDescriptor_9624c68e2b547544) }

var fileDescriptor_9624c68e2b547544 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0x69, 0x6b, 0xe7, 0x9a, 0xe9, 0xc0, 0x5c, 0x55, 0x45, 0x18, 0x83, 0xc1, 0xae, 0x7a,
	0xa1, 0x4f, 0xe0, 0x9f, 0x9b, 0x81, 0xa8, 0x4c, 0xaf, 0xbc, 0x09, 0x59, 0x72, 0x9c, 0xd1, 0xa6,
	0x09, 0xed, 0xa9, 0xb0, 0xa7, 0xf0, 0x4d, 0x7c, 0x46, 0x49, 0x52, 0xc1, 0xb9, 0x31, 0x6f, 0x7f,
	0xdf, 0x21, 0xf9, 0xf2, 0x3b, 0x21, 0x03, 0xa5, 0xf9, 0x12, 0x0a, 0x5b, 0x1b, 0x34, 0x94, 0x5a,
	0xb0, 0xd0, 0x56, 0xa5, 0xd2, 0x0a, 0x41, 0x16, 0x68, 0xa4, 0x19, 0x7f, 0x45, 0xe4, 0xe8, 0xba,
	0x06, 0x8e, 0x30, 0x73, 0x93, 0x0f, 0xbc, 0xe6, 0xba, 0xa1, 0xa7, 0x24, 0x7b, 0x51, 0x25, 0xb0,
	0x8a, 0x6b, 0xc8, 0xa3, 0x51, 0x34, 0xcd, 0xe6, 0x7d, 0x07, 0xee, 0xb8, 0x06, 0x17, 0x2e, 0x5a,
	0xf1, 0x0e, 0xc8, 0x94, 0xcc, 0xe3, 0x10, 0x06, 0x30, 0x93, 0x74, 0x42, 0x86, 0xc2, 0x54, 0x08,
	0x15, 0xb2, 0x12, 0xaa, 0x25, 0xbe, 0xe6, 0xc9, 0x28, 0x9a, 0x26, 0xf3, 0xc3, 0x8e, 0xde, 0x7a,
	0xe8, 0xce, 0xd0, 0x4a, 0x03, 0xc3, 0x95, 0x85, 0x7c, 0x2f, 0x9c, 0xe1, 0xc0, 0xd3, 0xca, 0xfa,
	0x0b, 0xcc, 0xe2, 0x0d, 0x84, 0xbf, 0x20, 0x0d, 0x61, 0x00, 0x33, 0x39, 0xfe, 0x8c, 0x49, 0xea,
	0xab, 0xee, 0x2e, 0x79, 0x46, 0x88, 0xf0, 0xcf, 0x92, 0x8c, 0x63, 0xd7, 0x32, 0xeb, 0xc8, 0x25,
	0xba, 0xb8, 0xb5, 0xf2, 0x27, 0x4e, 0x42, 0xdc, 0x91, 0x10, 0xab, 0x86, 0x49, 0x28, 0x01, 0x41,
	0xfa, 0x7e, 0xfd, 0x79, 0xa6, 0x9a, 0x9b, 0x00, 0xd6, 0x0d, 0xa4, 0x7f, 0x0c, 0x0c, 0x49, 0xac,
	0x64, 0xde, 0xf3, 0xaf, 0x8e, 0xd5, 0x36, 0x23, 0xfb, 0xff, 0x1a, 0xe9, 0xef, 0x32, 0x92, 0xad,
	0x1b, 0x39, 0x67, 0xe4, 0xc0, 0x0b, 0x79, 0x84, 0xfa, 0x43, 0x09, 0xa0, 0xf7, 0x64, 0xf0, 0x6b,
	0xa3, 0x74, 0x52, 0x6c, 0xae, 0xbd, 0xd8, 0x58, 0xf9, 0xc9, 0xf1, 0xb6, 0x31, 0x3f, 0x70, 0x95,
	0x3e, 0x27, 0xb5, 0x15, 0x8b, 0x9e, 0xff, 0x45, 0x17, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6b,
	0x75, 0x94, 0x76, 0x54, 0x02, 0x00, 0x00,
}
