// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/pepeunlimited/files/internal/app/ent/migrate"

	"github.com/pepeunlimited/files/internal/app/ent/dobuckets"

	"github.com/facebookincubator/ent/dialect"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// DoBuckets is the client for interacting with the DoBuckets builders.
	DoBuckets *DoBucketsClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	c := config{log: log.Println}
	c.options(opts...)
	return &Client{
		config:    c,
		Schema:    migrate.NewSchema(c.driver),
		DoBuckets: NewDoBucketsClient(c),
	}
}

// Open opens a connection to the database specified by the driver name and a
// driver-specific data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: tx, log: c.log, debug: c.debug}
	return &Tx{
		config:    cfg,
		DoBuckets: NewDoBucketsClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		DoBuckets.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true}
	return &Client{
		config:    cfg,
		Schema:    migrate.NewSchema(cfg.driver),
		DoBuckets: NewDoBucketsClient(cfg),
	}
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// DoBucketsClient is a client for the DoBuckets schema.
type DoBucketsClient struct {
	config
}

// NewDoBucketsClient returns a client for the DoBuckets from the given config.
func NewDoBucketsClient(c config) *DoBucketsClient {
	return &DoBucketsClient{config: c}
}

// Create returns a create builder for DoBuckets.
func (c *DoBucketsClient) Create() *DoBucketsCreate {
	return &DoBucketsCreate{config: c.config}
}

// Update returns an update builder for DoBuckets.
func (c *DoBucketsClient) Update() *DoBucketsUpdate {
	return &DoBucketsUpdate{config: c.config}
}

// UpdateOne returns an update builder for the given entity.
func (c *DoBucketsClient) UpdateOne(db *DoBuckets) *DoBucketsUpdateOne {
	return c.UpdateOneID(db.ID)
}

// UpdateOneID returns an update builder for the given id.
func (c *DoBucketsClient) UpdateOneID(id int) *DoBucketsUpdateOne {
	return &DoBucketsUpdateOne{config: c.config, id: id}
}

// Delete returns a delete builder for DoBuckets.
func (c *DoBucketsClient) Delete() *DoBucketsDelete {
	return &DoBucketsDelete{config: c.config}
}

// DeleteOne returns a delete builder for the given entity.
func (c *DoBucketsClient) DeleteOne(db *DoBuckets) *DoBucketsDeleteOne {
	return c.DeleteOneID(db.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *DoBucketsClient) DeleteOneID(id int) *DoBucketsDeleteOne {
	return &DoBucketsDeleteOne{c.Delete().Where(dobuckets.ID(id))}
}

// Create returns a query builder for DoBuckets.
func (c *DoBucketsClient) Query() *DoBucketsQuery {
	return &DoBucketsQuery{config: c.config}
}

// Get returns a DoBuckets entity by its id.
func (c *DoBucketsClient) Get(ctx context.Context, id int) (*DoBuckets, error) {
	return c.Query().Where(dobuckets.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DoBucketsClient) GetX(ctx context.Context, id int) *DoBuckets {
	db, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return db
}
