// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pepeunlimited/files/internal/app/ent/dobuckets"
	"github.com/pepeunlimited/files/internal/app/ent/predicate"
)

// DoBucketsQuery is the builder for querying DoBuckets entities.
type DoBucketsQuery struct {
	config
	limit      *int
	offset     *int
	order      []Order
	unique     []string
	predicates []predicate.DoBuckets
	// intermediate query.
	sql *sql.Selector
}

// Where adds a new predicate for the builder.
func (dbq *DoBucketsQuery) Where(ps ...predicate.DoBuckets) *DoBucketsQuery {
	dbq.predicates = append(dbq.predicates, ps...)
	return dbq
}

// Limit adds a limit step to the query.
func (dbq *DoBucketsQuery) Limit(limit int) *DoBucketsQuery {
	dbq.limit = &limit
	return dbq
}

// Offset adds an offset step to the query.
func (dbq *DoBucketsQuery) Offset(offset int) *DoBucketsQuery {
	dbq.offset = &offset
	return dbq
}

// Order adds an order step to the query.
func (dbq *DoBucketsQuery) Order(o ...Order) *DoBucketsQuery {
	dbq.order = append(dbq.order, o...)
	return dbq
}

// First returns the first DoBuckets entity in the query. Returns *ErrNotFound when no dobuckets was found.
func (dbq *DoBucketsQuery) First(ctx context.Context) (*DoBuckets, error) {
	dbs, err := dbq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(dbs) == 0 {
		return nil, &ErrNotFound{dobuckets.Label}
	}
	return dbs[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dbq *DoBucketsQuery) FirstX(ctx context.Context) *DoBuckets {
	db, err := dbq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return db
}

// FirstID returns the first DoBuckets id in the query. Returns *ErrNotFound when no id was found.
func (dbq *DoBucketsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dbq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &ErrNotFound{dobuckets.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (dbq *DoBucketsQuery) FirstXID(ctx context.Context) int {
	id, err := dbq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only DoBuckets entity in the query, returns an error if not exactly one entity was returned.
func (dbq *DoBucketsQuery) Only(ctx context.Context) (*DoBuckets, error) {
	dbs, err := dbq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(dbs) {
	case 1:
		return dbs[0], nil
	case 0:
		return nil, &ErrNotFound{dobuckets.Label}
	default:
		return nil, &ErrNotSingular{dobuckets.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dbq *DoBucketsQuery) OnlyX(ctx context.Context) *DoBuckets {
	db, err := dbq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return db
}

// OnlyID returns the only DoBuckets id in the query, returns an error if not exactly one id was returned.
func (dbq *DoBucketsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dbq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &ErrNotFound{dobuckets.Label}
	default:
		err = &ErrNotSingular{dobuckets.Label}
	}
	return
}

// OnlyXID is like OnlyID, but panics if an error occurs.
func (dbq *DoBucketsQuery) OnlyXID(ctx context.Context) int {
	id, err := dbq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DoBucketsSlice.
func (dbq *DoBucketsQuery) All(ctx context.Context) ([]*DoBuckets, error) {
	return dbq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (dbq *DoBucketsQuery) AllX(ctx context.Context) []*DoBuckets {
	dbs, err := dbq.All(ctx)
	if err != nil {
		panic(err)
	}
	return dbs
}

// IDs executes the query and returns a list of DoBuckets ids.
func (dbq *DoBucketsQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := dbq.Select(dobuckets.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dbq *DoBucketsQuery) IDsX(ctx context.Context) []int {
	ids, err := dbq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dbq *DoBucketsQuery) Count(ctx context.Context) (int, error) {
	return dbq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (dbq *DoBucketsQuery) CountX(ctx context.Context) int {
	count, err := dbq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dbq *DoBucketsQuery) Exist(ctx context.Context) (bool, error) {
	return dbq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (dbq *DoBucketsQuery) ExistX(ctx context.Context) bool {
	exist, err := dbq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dbq *DoBucketsQuery) Clone() *DoBucketsQuery {
	return &DoBucketsQuery{
		config:     dbq.config,
		limit:      dbq.limit,
		offset:     dbq.offset,
		order:      append([]Order{}, dbq.order...),
		unique:     append([]string{}, dbq.unique...),
		predicates: append([]predicate.DoBuckets{}, dbq.predicates...),
		// clone intermediate query.
		sql: dbq.sql.Clone(),
	}
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		BucketName string `json:"bucket_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DoBuckets.Query().
//		GroupBy(dobuckets.FieldBucketName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (dbq *DoBucketsQuery) GroupBy(field string, fields ...string) *DoBucketsGroupBy {
	group := &DoBucketsGroupBy{config: dbq.config}
	group.fields = append([]string{field}, fields...)
	group.sql = dbq.sqlQuery()
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		BucketName string `json:"bucket_name,omitempty"`
//	}
//
//	client.DoBuckets.Query().
//		Select(dobuckets.FieldBucketName).
//		Scan(ctx, &v)
//
func (dbq *DoBucketsQuery) Select(field string, fields ...string) *DoBucketsSelect {
	selector := &DoBucketsSelect{config: dbq.config}
	selector.fields = append([]string{field}, fields...)
	selector.sql = dbq.sqlQuery()
	return selector
}

func (dbq *DoBucketsQuery) sqlAll(ctx context.Context) ([]*DoBuckets, error) {
	var (
		nodes []*DoBuckets
		spec  = dbq.querySpec()
	)
	spec.ScanValues = func() []interface{} {
		node := &DoBuckets{config: dbq.config}
		nodes = append(nodes, node)
		return node.scanValues()
	}
	spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, dbq.driver, spec); err != nil {
		return nil, err
	}
	return nodes, nil
}

func (dbq *DoBucketsQuery) sqlCount(ctx context.Context) (int, error) {
	spec := dbq.querySpec()
	return sqlgraph.CountNodes(ctx, dbq.driver, spec)
}

func (dbq *DoBucketsQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := dbq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (dbq *DoBucketsQuery) querySpec() *sqlgraph.QuerySpec {
	spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   dobuckets.Table,
			Columns: dobuckets.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: dobuckets.FieldID,
			},
		},
		From:   dbq.sql,
		Unique: true,
	}
	if ps := dbq.predicates; len(ps) > 0 {
		spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dbq.limit; limit != nil {
		spec.Limit = *limit
	}
	if offset := dbq.offset; offset != nil {
		spec.Offset = *offset
	}
	if ps := dbq.order; len(ps) > 0 {
		spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return spec
}

func (dbq *DoBucketsQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(dbq.driver.Dialect())
	t1 := builder.Table(dobuckets.Table)
	selector := builder.Select(t1.Columns(dobuckets.Columns...)...).From(t1)
	if dbq.sql != nil {
		selector = dbq.sql
		selector.Select(selector.Columns(dobuckets.Columns...)...)
	}
	for _, p := range dbq.predicates {
		p(selector)
	}
	for _, p := range dbq.order {
		p(selector)
	}
	if offset := dbq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dbq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DoBucketsGroupBy is the builder for group-by DoBuckets entities.
type DoBucketsGroupBy struct {
	config
	fields []string
	fns    []Aggregate
	// intermediate query.
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dbgb *DoBucketsGroupBy) Aggregate(fns ...Aggregate) *DoBucketsGroupBy {
	dbgb.fns = append(dbgb.fns, fns...)
	return dbgb
}

// Scan applies the group-by query and scan the result into the given value.
func (dbgb *DoBucketsGroupBy) Scan(ctx context.Context, v interface{}) error {
	return dbgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (dbgb *DoBucketsGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := dbgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (dbgb *DoBucketsGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(dbgb.fields) > 1 {
		return nil, errors.New("ent: DoBucketsGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := dbgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (dbgb *DoBucketsGroupBy) StringsX(ctx context.Context) []string {
	v, err := dbgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (dbgb *DoBucketsGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(dbgb.fields) > 1 {
		return nil, errors.New("ent: DoBucketsGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := dbgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (dbgb *DoBucketsGroupBy) IntsX(ctx context.Context) []int {
	v, err := dbgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (dbgb *DoBucketsGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(dbgb.fields) > 1 {
		return nil, errors.New("ent: DoBucketsGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := dbgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (dbgb *DoBucketsGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := dbgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (dbgb *DoBucketsGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(dbgb.fields) > 1 {
		return nil, errors.New("ent: DoBucketsGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := dbgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (dbgb *DoBucketsGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := dbgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dbgb *DoBucketsGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := dbgb.sqlQuery().Query()
	if err := dbgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (dbgb *DoBucketsGroupBy) sqlQuery() *sql.Selector {
	selector := dbgb.sql
	columns := make([]string, 0, len(dbgb.fields)+len(dbgb.fns))
	columns = append(columns, dbgb.fields...)
	for _, fn := range dbgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(dbgb.fields...)
}

// DoBucketsSelect is the builder for select fields of DoBuckets entities.
type DoBucketsSelect struct {
	config
	fields []string
	// intermediate queries.
	sql *sql.Selector
}

// Scan applies the selector query and scan the result into the given value.
func (dbs *DoBucketsSelect) Scan(ctx context.Context, v interface{}) error {
	return dbs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (dbs *DoBucketsSelect) ScanX(ctx context.Context, v interface{}) {
	if err := dbs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (dbs *DoBucketsSelect) Strings(ctx context.Context) ([]string, error) {
	if len(dbs.fields) > 1 {
		return nil, errors.New("ent: DoBucketsSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := dbs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (dbs *DoBucketsSelect) StringsX(ctx context.Context) []string {
	v, err := dbs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (dbs *DoBucketsSelect) Ints(ctx context.Context) ([]int, error) {
	if len(dbs.fields) > 1 {
		return nil, errors.New("ent: DoBucketsSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := dbs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (dbs *DoBucketsSelect) IntsX(ctx context.Context) []int {
	v, err := dbs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (dbs *DoBucketsSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(dbs.fields) > 1 {
		return nil, errors.New("ent: DoBucketsSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := dbs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (dbs *DoBucketsSelect) Float64sX(ctx context.Context) []float64 {
	v, err := dbs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (dbs *DoBucketsSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(dbs.fields) > 1 {
		return nil, errors.New("ent: DoBucketsSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := dbs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (dbs *DoBucketsSelect) BoolsX(ctx context.Context) []bool {
	v, err := dbs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dbs *DoBucketsSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := dbs.sqlQuery().Query()
	if err := dbs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (dbs *DoBucketsSelect) sqlQuery() sql.Querier {
	selector := dbs.sql
	selector.Select(selector.Columns(dbs.fields...)...)
	return selector
}
