// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pepeunlimited/files/internal/app/ent/dobuckets"
	"github.com/pepeunlimited/files/internal/app/ent/predicate"
)

// DoBucketsDelete is the builder for deleting a DoBuckets entity.
type DoBucketsDelete struct {
	config
	predicates []predicate.DoBuckets
}

// Where adds a new predicate to the delete builder.
func (dbd *DoBucketsDelete) Where(ps ...predicate.DoBuckets) *DoBucketsDelete {
	dbd.predicates = append(dbd.predicates, ps...)
	return dbd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dbd *DoBucketsDelete) Exec(ctx context.Context) (int, error) {
	return dbd.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (dbd *DoBucketsDelete) ExecX(ctx context.Context) int {
	n, err := dbd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dbd *DoBucketsDelete) sqlExec(ctx context.Context) (int, error) {
	spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: dobuckets.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: dobuckets.FieldID,
			},
		},
	}
	if ps := dbd.predicates; len(ps) > 0 {
		spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, dbd.driver, spec)
}

// DoBucketsDeleteOne is the builder for deleting a single DoBuckets entity.
type DoBucketsDeleteOne struct {
	dbd *DoBucketsDelete
}

// Exec executes the deletion query.
func (dbdo *DoBucketsDeleteOne) Exec(ctx context.Context) error {
	n, err := dbdo.dbd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &ErrNotFound{dobuckets.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dbdo *DoBucketsDeleteOne) ExecX(ctx context.Context) {
	dbdo.dbd.ExecX(ctx)
}
