// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pepeunlimited/files/internal/app/app1/ent/buckets"
	"github.com/pepeunlimited/files/internal/app/app1/ent/files"
	"github.com/pepeunlimited/files/internal/app/app1/ent/predicate"
)

// BucketsUpdate is the builder for updating Buckets entities.
type BucketsUpdate struct {
	config
	name              *string
	endpoint          *string
	cdn_endpoint      *string
	clearcdn_endpoint bool
	created_at        *time.Time
	files             map[int]struct{}
	removedFiles      map[int]struct{}
	predicates        []predicate.Buckets
}

// Where adds a new predicate for the builder.
func (bu *BucketsUpdate) Where(ps ...predicate.Buckets) *BucketsUpdate {
	bu.predicates = append(bu.predicates, ps...)
	return bu
}

// SetName sets the name field.
func (bu *BucketsUpdate) SetName(s string) *BucketsUpdate {
	bu.name = &s
	return bu
}

// SetEndpoint sets the endpoint field.
func (bu *BucketsUpdate) SetEndpoint(s string) *BucketsUpdate {
	bu.endpoint = &s
	return bu
}

// SetCdnEndpoint sets the cdn_endpoint field.
func (bu *BucketsUpdate) SetCdnEndpoint(s string) *BucketsUpdate {
	bu.cdn_endpoint = &s
	return bu
}

// SetNillableCdnEndpoint sets the cdn_endpoint field if the given value is not nil.
func (bu *BucketsUpdate) SetNillableCdnEndpoint(s *string) *BucketsUpdate {
	if s != nil {
		bu.SetCdnEndpoint(*s)
	}
	return bu
}

// ClearCdnEndpoint clears the value of cdn_endpoint.
func (bu *BucketsUpdate) ClearCdnEndpoint() *BucketsUpdate {
	bu.cdn_endpoint = nil
	bu.clearcdn_endpoint = true
	return bu
}

// SetCreatedAt sets the created_at field.
func (bu *BucketsUpdate) SetCreatedAt(t time.Time) *BucketsUpdate {
	bu.created_at = &t
	return bu
}

// AddFileIDs adds the files edge to Files by ids.
func (bu *BucketsUpdate) AddFileIDs(ids ...int) *BucketsUpdate {
	if bu.files == nil {
		bu.files = make(map[int]struct{})
	}
	for i := range ids {
		bu.files[ids[i]] = struct{}{}
	}
	return bu
}

// AddFiles adds the files edges to Files.
func (bu *BucketsUpdate) AddFiles(f ...*Files) *BucketsUpdate {
	ids := make([]int, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return bu.AddFileIDs(ids...)
}

// RemoveFileIDs removes the files edge to Files by ids.
func (bu *BucketsUpdate) RemoveFileIDs(ids ...int) *BucketsUpdate {
	if bu.removedFiles == nil {
		bu.removedFiles = make(map[int]struct{})
	}
	for i := range ids {
		bu.removedFiles[ids[i]] = struct{}{}
	}
	return bu
}

// RemoveFiles removes files edges to Files.
func (bu *BucketsUpdate) RemoveFiles(f ...*Files) *BucketsUpdate {
	ids := make([]int, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return bu.RemoveFileIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (bu *BucketsUpdate) Save(ctx context.Context) (int, error) {
	if bu.name != nil {
		if err := buckets.NameValidator(*bu.name); err != nil {
			return 0, fmt.Errorf("ent: validator failed for field \"name\": %v", err)
		}
	}
	if bu.endpoint != nil {
		if err := buckets.EndpointValidator(*bu.endpoint); err != nil {
			return 0, fmt.Errorf("ent: validator failed for field \"endpoint\": %v", err)
		}
	}
	return bu.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BucketsUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BucketsUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BucketsUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bu *BucketsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   buckets.Table,
			Columns: buckets.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: buckets.FieldID,
			},
		},
	}
	if ps := bu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value := bu.name; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: buckets.FieldName,
		})
	}
	if value := bu.endpoint; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: buckets.FieldEndpoint,
		})
	}
	if value := bu.cdn_endpoint; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: buckets.FieldCdnEndpoint,
		})
	}
	if bu.clearcdn_endpoint {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: buckets.FieldCdnEndpoint,
		})
	}
	if value := bu.created_at; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  *value,
			Column: buckets.FieldCreatedAt,
		})
	}
	if nodes := bu.removedFiles; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   buckets.FilesTable,
			Columns: []string{buckets.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: files.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.files; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   buckets.FilesTable,
			Columns: []string{buckets.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: files.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// BucketsUpdateOne is the builder for updating a single Buckets entity.
type BucketsUpdateOne struct {
	config
	id                int
	name              *string
	endpoint          *string
	cdn_endpoint      *string
	clearcdn_endpoint bool
	created_at        *time.Time
	files             map[int]struct{}
	removedFiles      map[int]struct{}
}

// SetName sets the name field.
func (buo *BucketsUpdateOne) SetName(s string) *BucketsUpdateOne {
	buo.name = &s
	return buo
}

// SetEndpoint sets the endpoint field.
func (buo *BucketsUpdateOne) SetEndpoint(s string) *BucketsUpdateOne {
	buo.endpoint = &s
	return buo
}

// SetCdnEndpoint sets the cdn_endpoint field.
func (buo *BucketsUpdateOne) SetCdnEndpoint(s string) *BucketsUpdateOne {
	buo.cdn_endpoint = &s
	return buo
}

// SetNillableCdnEndpoint sets the cdn_endpoint field if the given value is not nil.
func (buo *BucketsUpdateOne) SetNillableCdnEndpoint(s *string) *BucketsUpdateOne {
	if s != nil {
		buo.SetCdnEndpoint(*s)
	}
	return buo
}

// ClearCdnEndpoint clears the value of cdn_endpoint.
func (buo *BucketsUpdateOne) ClearCdnEndpoint() *BucketsUpdateOne {
	buo.cdn_endpoint = nil
	buo.clearcdn_endpoint = true
	return buo
}

// SetCreatedAt sets the created_at field.
func (buo *BucketsUpdateOne) SetCreatedAt(t time.Time) *BucketsUpdateOne {
	buo.created_at = &t
	return buo
}

// AddFileIDs adds the files edge to Files by ids.
func (buo *BucketsUpdateOne) AddFileIDs(ids ...int) *BucketsUpdateOne {
	if buo.files == nil {
		buo.files = make(map[int]struct{})
	}
	for i := range ids {
		buo.files[ids[i]] = struct{}{}
	}
	return buo
}

// AddFiles adds the files edges to Files.
func (buo *BucketsUpdateOne) AddFiles(f ...*Files) *BucketsUpdateOne {
	ids := make([]int, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return buo.AddFileIDs(ids...)
}

// RemoveFileIDs removes the files edge to Files by ids.
func (buo *BucketsUpdateOne) RemoveFileIDs(ids ...int) *BucketsUpdateOne {
	if buo.removedFiles == nil {
		buo.removedFiles = make(map[int]struct{})
	}
	for i := range ids {
		buo.removedFiles[ids[i]] = struct{}{}
	}
	return buo
}

// RemoveFiles removes files edges to Files.
func (buo *BucketsUpdateOne) RemoveFiles(f ...*Files) *BucketsUpdateOne {
	ids := make([]int, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return buo.RemoveFileIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (buo *BucketsUpdateOne) Save(ctx context.Context) (*Buckets, error) {
	if buo.name != nil {
		if err := buckets.NameValidator(*buo.name); err != nil {
			return nil, fmt.Errorf("ent: validator failed for field \"name\": %v", err)
		}
	}
	if buo.endpoint != nil {
		if err := buckets.EndpointValidator(*buo.endpoint); err != nil {
			return nil, fmt.Errorf("ent: validator failed for field \"endpoint\": %v", err)
		}
	}
	return buo.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BucketsUpdateOne) SaveX(ctx context.Context) *Buckets {
	b, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return b
}

// Exec executes the query on the entity.
func (buo *BucketsUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BucketsUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (buo *BucketsUpdateOne) sqlSave(ctx context.Context) (b *Buckets, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   buckets.Table,
			Columns: buckets.Columns,
			ID: &sqlgraph.FieldSpec{
				Value:  buo.id,
				Type:   field.TypeInt,
				Column: buckets.FieldID,
			},
		},
	}
	if value := buo.name; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: buckets.FieldName,
		})
	}
	if value := buo.endpoint; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: buckets.FieldEndpoint,
		})
	}
	if value := buo.cdn_endpoint; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: buckets.FieldCdnEndpoint,
		})
	}
	if buo.clearcdn_endpoint {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: buckets.FieldCdnEndpoint,
		})
	}
	if value := buo.created_at; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  *value,
			Column: buckets.FieldCreatedAt,
		})
	}
	if nodes := buo.removedFiles; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   buckets.FilesTable,
			Columns: []string{buckets.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: files.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.files; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   buckets.FilesTable,
			Columns: []string{buckets.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: files.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	b = &Buckets{config: buo.config}
	_spec.Assign = b.assignValues
	_spec.ScanValues = b.scanValues()
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return b, nil
}
