// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pepeunlimited/files/internal/app/app1/ent/buckets"
	"github.com/pepeunlimited/files/internal/app/app1/ent/predicate"
)

// BucketsDelete is the builder for deleting a Buckets entity.
type BucketsDelete struct {
	config
	predicates []predicate.Buckets
}

// Where adds a new predicate to the delete builder.
func (bd *BucketsDelete) Where(ps ...predicate.Buckets) *BucketsDelete {
	bd.predicates = append(bd.predicates, ps...)
	return bd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bd *BucketsDelete) Exec(ctx context.Context) (int, error) {
	return bd.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (bd *BucketsDelete) ExecX(ctx context.Context) int {
	n, err := bd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bd *BucketsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: buckets.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: buckets.FieldID,
			},
		},
	}
	if ps := bd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, bd.driver, _spec)
}

// BucketsDeleteOne is the builder for deleting a single Buckets entity.
type BucketsDeleteOne struct {
	bd *BucketsDelete
}

// Exec executes the deletion query.
func (bdo *BucketsDeleteOne) Exec(ctx context.Context) error {
	n, err := bdo.bd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &ErrNotFound{buckets.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bdo *BucketsDeleteOne) ExecX(ctx context.Context) {
	bdo.bd.ExecX(ctx)
}
