// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Files is the predicate function for files builders.
type Files func(*sql.Selector)

// Spaces is the predicate function for spaces builders.
type Spaces func(*sql.Selector)
