// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Buckets is the predicate function for buckets builders.
type Buckets func(*sql.Selector)

// Files is the predicate function for files builders.
type Files func(*sql.Selector)
