// Code generated by protoc-gen-go. DO NOT EDIT.
// source: files.proto

package filesrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateBucketParams struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Endpoint             string   `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBucketParams) Reset()         { *m = CreateBucketParams{} }
func (m *CreateBucketParams) String() string { return proto.CompactTextString(m) }
func (*CreateBucketParams) ProtoMessage()    {}
func (*CreateBucketParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{0}
}

func (m *CreateBucketParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBucketParams.Unmarshal(m, b)
}
func (m *CreateBucketParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBucketParams.Marshal(b, m, deterministic)
}
func (m *CreateBucketParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBucketParams.Merge(m, src)
}
func (m *CreateBucketParams) XXX_Size() int {
	return xxx_messageInfo_CreateBucketParams.Size(m)
}
func (m *CreateBucketParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBucketParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBucketParams proto.InternalMessageInfo

func (m *CreateBucketParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateBucketParams) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

type CreateBucketResponse struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	CdnEndpoint          string   `protobuf:"bytes,2,opt,name=cdn_endpoint,json=cdnEndpoint,proto3" json:"cdn_endpoint,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	BucketId             int64    `protobuf:"varint,4,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBucketResponse) Reset()         { *m = CreateBucketResponse{} }
func (m *CreateBucketResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBucketResponse) ProtoMessage()    {}
func (*CreateBucketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{1}
}

func (m *CreateBucketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBucketResponse.Unmarshal(m, b)
}
func (m *CreateBucketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBucketResponse.Marshal(b, m, deterministic)
}
func (m *CreateBucketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBucketResponse.Merge(m, src)
}
func (m *CreateBucketResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBucketResponse.Size(m)
}
func (m *CreateBucketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBucketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBucketResponse proto.InternalMessageInfo

func (m *CreateBucketResponse) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *CreateBucketResponse) GetCdnEndpoint() string {
	if m != nil {
		return m.CdnEndpoint
	}
	return ""
}

func (m *CreateBucketResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateBucketResponse) GetBucketId() int64 {
	if m != nil {
		return m.BucketId
	}
	return 0
}

type GetFileParams struct {
	FileId               *wrappers.Int64Value `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Filename             *Filename            `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetFileParams) Reset()         { *m = GetFileParams{} }
func (m *GetFileParams) String() string { return proto.CompactTextString(m) }
func (*GetFileParams) ProtoMessage()    {}
func (*GetFileParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{2}
}

func (m *GetFileParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileParams.Unmarshal(m, b)
}
func (m *GetFileParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileParams.Marshal(b, m, deterministic)
}
func (m *GetFileParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileParams.Merge(m, src)
}
func (m *GetFileParams) XXX_Size() int {
	return xxx_messageInfo_GetFileParams.Size(m)
}
func (m *GetFileParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileParams proto.InternalMessageInfo

func (m *GetFileParams) GetFileId() *wrappers.Int64Value {
	if m != nil {
		return m.FileId
	}
	return nil
}

func (m *GetFileParams) GetFilename() *Filename {
	if m != nil {
		return m.Filename
	}
	return nil
}

type GetFilesParams struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            int64    `protobuf:"varint,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFilesParams) Reset()         { *m = GetFilesParams{} }
func (m *GetFilesParams) String() string { return proto.CompactTextString(m) }
func (*GetFilesParams) ProtoMessage()    {}
func (*GetFilesParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{3}
}

func (m *GetFilesParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFilesParams.Unmarshal(m, b)
}
func (m *GetFilesParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFilesParams.Marshal(b, m, deterministic)
}
func (m *GetFilesParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFilesParams.Merge(m, src)
}
func (m *GetFilesParams) XXX_Size() int {
	return xxx_messageInfo_GetFilesParams.Size(m)
}
func (m *GetFilesParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFilesParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetFilesParams proto.InternalMessageInfo

func (m *GetFilesParams) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetFilesParams) GetPageToken() int64 {
	if m != nil {
		return m.PageToken
	}
	return 0
}

type GetFilesResponse struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFilesResponse) Reset()         { *m = GetFilesResponse{} }
func (m *GetFilesResponse) String() string { return proto.CompactTextString(m) }
func (*GetFilesResponse) ProtoMessage()    {}
func (*GetFilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{4}
}

func (m *GetFilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFilesResponse.Unmarshal(m, b)
}
func (m *GetFilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFilesResponse.Marshal(b, m, deterministic)
}
func (m *GetFilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFilesResponse.Merge(m, src)
}
func (m *GetFilesResponse) XXX_Size() int {
	return xxx_messageInfo_GetFilesResponse.Size(m)
}
func (m *GetFilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFilesResponse proto.InternalMessageInfo

func (m *GetFilesResponse) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type GetBucketsParams struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            int64    `protobuf:"varint,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBucketsParams) Reset()         { *m = GetBucketsParams{} }
func (m *GetBucketsParams) String() string { return proto.CompactTextString(m) }
func (*GetBucketsParams) ProtoMessage()    {}
func (*GetBucketsParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{5}
}

func (m *GetBucketsParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBucketsParams.Unmarshal(m, b)
}
func (m *GetBucketsParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBucketsParams.Marshal(b, m, deterministic)
}
func (m *GetBucketsParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBucketsParams.Merge(m, src)
}
func (m *GetBucketsParams) XXX_Size() int {
	return xxx_messageInfo_GetBucketsParams.Size(m)
}
func (m *GetBucketsParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBucketsParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetBucketsParams proto.InternalMessageInfo

func (m *GetBucketsParams) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetBucketsParams) GetPageToken() int64 {
	if m != nil {
		return m.PageToken
	}
	return 0
}

type GetBucketsResponse struct {
	Buckets              []*Bucket `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetBucketsResponse) Reset()         { *m = GetBucketsResponse{} }
func (m *GetBucketsResponse) String() string { return proto.CompactTextString(m) }
func (*GetBucketsResponse) ProtoMessage()    {}
func (*GetBucketsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{6}
}

func (m *GetBucketsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBucketsResponse.Unmarshal(m, b)
}
func (m *GetBucketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBucketsResponse.Marshal(b, m, deterministic)
}
func (m *GetBucketsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBucketsResponse.Merge(m, src)
}
func (m *GetBucketsResponse) XXX_Size() int {
	return xxx_messageInfo_GetBucketsResponse.Size(m)
}
func (m *GetBucketsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBucketsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBucketsResponse proto.InternalMessageInfo

func (m *GetBucketsResponse) GetBuckets() []*Bucket {
	if m != nil {
		return m.Buckets
	}
	return nil
}

type Bucket struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bucket) Reset()         { *m = Bucket{} }
func (m *Bucket) String() string { return proto.CompactTextString(m) }
func (*Bucket) ProtoMessage()    {}
func (*Bucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{7}
}

func (m *Bucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucket.Unmarshal(m, b)
}
func (m *Bucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucket.Marshal(b, m, deterministic)
}
func (m *Bucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucket.Merge(m, src)
}
func (m *Bucket) XXX_Size() int {
	return xxx_messageInfo_Bucket.Size(m)
}
func (m *Bucket) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucket.DiscardUnknown(m)
}

var xxx_messageInfo_Bucket proto.InternalMessageInfo

func (m *Bucket) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Bucket) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CutParams struct {
	ToSpacesName         *wrappers.StringValue `protobuf:"bytes,1,opt,name=to_spaces_name,json=toSpacesName,proto3" json:"to_spaces_name,omitempty"`
	FileId               int64                 `protobuf:"varint,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Filename             *Filename             `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	ToSpacesId           *wrappers.Int64Value  `protobuf:"bytes,4,opt,name=to_spaces_id,json=toSpacesId,proto3" json:"to_spaces_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CutParams) Reset()         { *m = CutParams{} }
func (m *CutParams) String() string { return proto.CompactTextString(m) }
func (*CutParams) ProtoMessage()    {}
func (*CutParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{8}
}

func (m *CutParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CutParams.Unmarshal(m, b)
}
func (m *CutParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CutParams.Marshal(b, m, deterministic)
}
func (m *CutParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CutParams.Merge(m, src)
}
func (m *CutParams) XXX_Size() int {
	return xxx_messageInfo_CutParams.Size(m)
}
func (m *CutParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CutParams.DiscardUnknown(m)
}

var xxx_messageInfo_CutParams proto.InternalMessageInfo

func (m *CutParams) GetToSpacesName() *wrappers.StringValue {
	if m != nil {
		return m.ToSpacesName
	}
	return nil
}

func (m *CutParams) GetFileId() int64 {
	if m != nil {
		return m.FileId
	}
	return 0
}

func (m *CutParams) GetFilename() *Filename {
	if m != nil {
		return m.Filename
	}
	return nil
}

func (m *CutParams) GetToSpacesId() *wrappers.Int64Value {
	if m != nil {
		return m.ToSpacesId
	}
	return nil
}

type CutResponse struct {
	NewBucketName        string   `protobuf:"bytes,1,opt,name=new_bucket_name,json=newBucketName,proto3" json:"new_bucket_name,omitempty"`
	NewBucketId          int64    `protobuf:"varint,2,opt,name=new_bucket_id,json=newBucketId,proto3" json:"new_bucket_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CutResponse) Reset()         { *m = CutResponse{} }
func (m *CutResponse) String() string { return proto.CompactTextString(m) }
func (*CutResponse) ProtoMessage()    {}
func (*CutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{9}
}

func (m *CutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CutResponse.Unmarshal(m, b)
}
func (m *CutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CutResponse.Marshal(b, m, deterministic)
}
func (m *CutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CutResponse.Merge(m, src)
}
func (m *CutResponse) XXX_Size() int {
	return xxx_messageInfo_CutResponse.Size(m)
}
func (m *CutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CutResponse proto.InternalMessageInfo

func (m *CutResponse) GetNewBucketName() string {
	if m != nil {
		return m.NewBucketName
	}
	return ""
}

func (m *CutResponse) GetNewBucketId() int64 {
	if m != nil {
		return m.NewBucketId
	}
	return 0
}

type WipeParams struct {
	BucketName           string   `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	IsDeleteSpaces       bool     `protobuf:"varint,2,opt,name=is_delete_spaces,json=isDeleteSpaces,proto3" json:"is_delete_spaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WipeParams) Reset()         { *m = WipeParams{} }
func (m *WipeParams) String() string { return proto.CompactTextString(m) }
func (*WipeParams) ProtoMessage()    {}
func (*WipeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{10}
}

func (m *WipeParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WipeParams.Unmarshal(m, b)
}
func (m *WipeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WipeParams.Marshal(b, m, deterministic)
}
func (m *WipeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WipeParams.Merge(m, src)
}
func (m *WipeParams) XXX_Size() int {
	return xxx_messageInfo_WipeParams.Size(m)
}
func (m *WipeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_WipeParams.DiscardUnknown(m)
}

var xxx_messageInfo_WipeParams proto.InternalMessageInfo

func (m *WipeParams) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *WipeParams) GetIsDeleteSpaces() bool {
	if m != nil {
		return m.IsDeleteSpaces
	}
	return false
}

type WipeParamsResponse struct {
	DeletedCount         int64    `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WipeParamsResponse) Reset()         { *m = WipeParamsResponse{} }
func (m *WipeParamsResponse) String() string { return proto.CompactTextString(m) }
func (*WipeParamsResponse) ProtoMessage()    {}
func (*WipeParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{11}
}

func (m *WipeParamsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WipeParamsResponse.Unmarshal(m, b)
}
func (m *WipeParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WipeParamsResponse.Marshal(b, m, deterministic)
}
func (m *WipeParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WipeParamsResponse.Merge(m, src)
}
func (m *WipeParamsResponse) XXX_Size() int {
	return xxx_messageInfo_WipeParamsResponse.Size(m)
}
func (m *WipeParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WipeParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WipeParamsResponse proto.InternalMessageInfo

func (m *WipeParamsResponse) GetDeletedCount() int64 {
	if m != nil {
		return m.DeletedCount
	}
	return 0
}

type DeleteParams struct {
	FileId               *wrappers.Int64Value `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Filename             *Filename            `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	IsPermanent          bool                 `protobuf:"varint,3,opt,name=is_permanent,json=isPermanent,proto3" json:"is_permanent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteParams) Reset()         { *m = DeleteParams{} }
func (m *DeleteParams) String() string { return proto.CompactTextString(m) }
func (*DeleteParams) ProtoMessage()    {}
func (*DeleteParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{12}
}

func (m *DeleteParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteParams.Unmarshal(m, b)
}
func (m *DeleteParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteParams.Marshal(b, m, deterministic)
}
func (m *DeleteParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteParams.Merge(m, src)
}
func (m *DeleteParams) XXX_Size() int {
	return xxx_messageInfo_DeleteParams.Size(m)
}
func (m *DeleteParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteParams.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteParams proto.InternalMessageInfo

func (m *DeleteParams) GetFileId() *wrappers.Int64Value {
	if m != nil {
		return m.FileId
	}
	return nil
}

func (m *DeleteParams) GetFilename() *Filename {
	if m != nil {
		return m.Filename
	}
	return nil
}

func (m *DeleteParams) GetIsPermanent() bool {
	if m != nil {
		return m.IsPermanent
	}
	return false
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{13}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

type Filename struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BucketId             *wrappers.Int64Value  `protobuf:"bytes,2,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	BucketName           *wrappers.StringValue `protobuf:"bytes,3,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Filename) Reset()         { *m = Filename{} }
func (m *Filename) String() string { return proto.CompactTextString(m) }
func (*Filename) ProtoMessage()    {}
func (*Filename) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{14}
}

func (m *Filename) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filename.Unmarshal(m, b)
}
func (m *Filename) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filename.Marshal(b, m, deterministic)
}
func (m *Filename) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filename.Merge(m, src)
}
func (m *Filename) XXX_Size() int {
	return xxx_messageInfo_Filename.Size(m)
}
func (m *Filename) XXX_DiscardUnknown() {
	xxx_messageInfo_Filename.DiscardUnknown(m)
}

var xxx_messageInfo_Filename proto.InternalMessageInfo

func (m *Filename) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Filename) GetBucketId() *wrappers.Int64Value {
	if m != nil {
		return m.BucketId
	}
	return nil
}

func (m *Filename) GetBucketName() *wrappers.StringValue {
	if m != nil {
		return m.BucketName
	}
	return nil
}

type File struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	MimeType             string   `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FileSize             int64    `protobuf:"varint,6,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	UserId               int64    `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsDraft              bool     `protobuf:"varint,8,opt,name=is_draft,json=isDraft,proto3" json:"is_draft,omitempty"`
	SpacesId             int64    `protobuf:"varint,9,opt,name=spaces_id,json=spacesId,proto3" json:"spaces_id,omitempty"`
	FileUrl              string   `protobuf:"bytes,10,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{15}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *File) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *File) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *File) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *File) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}

func (m *File) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *File) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *File) GetIsDraft() bool {
	if m != nil {
		return m.IsDraft
	}
	return false
}

func (m *File) GetSpacesId() int64 {
	if m != nil {
		return m.SpacesId
	}
	return 0
}

func (m *File) GetFileUrl() string {
	if m != nil {
		return m.FileUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateBucketParams)(nil), "pepeunlimited.files.CreateBucketParams")
	proto.RegisterType((*CreateBucketResponse)(nil), "pepeunlimited.files.CreateBucketResponse")
	proto.RegisterType((*GetFileParams)(nil), "pepeunlimited.files.GetFileParams")
	proto.RegisterType((*GetFilesParams)(nil), "pepeunlimited.files.GetFilesParams")
	proto.RegisterType((*GetFilesResponse)(nil), "pepeunlimited.files.GetFilesResponse")
	proto.RegisterType((*GetBucketsParams)(nil), "pepeunlimited.files.GetBucketsParams")
	proto.RegisterType((*GetBucketsResponse)(nil), "pepeunlimited.files.GetBucketsResponse")
	proto.RegisterType((*Bucket)(nil), "pepeunlimited.files.Bucket")
	proto.RegisterType((*CutParams)(nil), "pepeunlimited.files.CutParams")
	proto.RegisterType((*CutResponse)(nil), "pepeunlimited.files.CutResponse")
	proto.RegisterType((*WipeParams)(nil), "pepeunlimited.files.WipeParams")
	proto.RegisterType((*WipeParamsResponse)(nil), "pepeunlimited.files.WipeParamsResponse")
	proto.RegisterType((*DeleteParams)(nil), "pepeunlimited.files.DeleteParams")
	proto.RegisterType((*DeleteResponse)(nil), "pepeunlimited.files.DeleteResponse")
	proto.RegisterType((*Filename)(nil), "pepeunlimited.files.Filename")
	proto.RegisterType((*File)(nil), "pepeunlimited.files.File")
}

func init() { proto.RegisterFile("files.proto", fileDescriptor_cac8f32ecfdd343c) }

var fileDescriptor_cac8f32ecfdd343c = []byte{
	// 893 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x5d, 0x8f, 0xdb, 0x44,
	0x14, 0x95, 0xe3, 0x6c, 0xe2, 0x5c, 0x67, 0xc3, 0x6a, 0x40, 0x6a, 0xea, 0xb0, 0x6d, 0x3a, 0x2b,
	0x20, 0x48, 0x28, 0x2b, 0x85, 0x82, 0xe8, 0x43, 0x1f, 0xba, 0x59, 0x5a, 0x22, 0x50, 0xb5, 0x72,
	0x4a, 0x2b, 0x10, 0x92, 0xe5, 0xd8, 0xb3, 0xd1, 0xa8, 0x8e, 0x6d, 0x79, 0xc6, 0xac, 0xda, 0x27,
	0x9e, 0xf8, 0x09, 0xf0, 0xce, 0x1f, 0x43, 0xe2, 0x97, 0xa0, 0xf9, 0xf0, 0x47, 0x1a, 0x67, 0x03,
	0x12, 0x12, 0x6f, 0xeb, 0x3b, 0xe7, 0x9e, 0x39, 0x73, 0x3f, 0xce, 0x06, 0xec, 0x6b, 0x1a, 0x11,
	0x36, 0x4d, 0xb3, 0x84, 0x27, 0xe8, 0xfd, 0x94, 0xa4, 0x24, 0x8f, 0x23, 0xba, 0xa1, 0x9c, 0x84,
	0x53, 0x79, 0xe4, 0xdc, 0x5b, 0x27, 0xc9, 0x3a, 0x22, 0xe7, 0x12, 0xb2, 0xca, 0xaf, 0xcf, 0x6f,
	0x32, 0x3f, 0x4d, 0x49, 0xa6, 0x93, 0xf0, 0x25, 0xa0, 0x79, 0x46, 0x7c, 0x4e, 0x2e, 0xf2, 0xe0,
	0x35, 0xe1, 0x57, 0x7e, 0xe6, 0x6f, 0x18, 0x42, 0xd0, 0x8e, 0xfd, 0x0d, 0x19, 0x1a, 0x63, 0x63,
	0xd2, 0x73, 0xe5, 0xdf, 0xc8, 0x01, 0x8b, 0xc4, 0x61, 0x9a, 0xd0, 0x98, 0x0f, 0x5b, 0x32, 0x5e,
	0x7e, 0xe3, 0x5f, 0x0d, 0xf8, 0xa0, 0x4e, 0xe3, 0x12, 0x96, 0x26, 0x31, 0xdb, 0x4e, 0x32, 0xb6,
	0x93, 0xd0, 0x03, 0xe8, 0x07, 0x61, 0xec, 0xbd, 0x43, 0x6a, 0x07, 0x61, 0xfc, 0x75, 0x01, 0x29,
	0x74, 0x98, 0x35, 0x1d, 0x23, 0xe8, 0xad, 0xe4, 0x25, 0x1e, 0x0d, 0x87, 0xed, 0xb1, 0x31, 0x31,
	0x5d, 0x4b, 0x05, 0x16, 0x21, 0xfe, 0xc5, 0x80, 0xe3, 0x67, 0x84, 0x3f, 0xa5, 0x11, 0xd1, 0x4f,
	0x79, 0x08, 0x5d, 0x51, 0x09, 0x01, 0x16, 0x02, 0xec, 0xd9, 0x68, 0xaa, 0x4a, 0x32, 0x2d, 0x4a,
	0x32, 0x5d, 0xc4, 0xfc, 0xcb, 0x87, 0x2f, 0xfd, 0x28, 0x27, 0x6e, 0x47, 0x60, 0x17, 0x21, 0x7a,
	0x04, 0x96, 0xf8, 0x4b, 0x5e, 0xde, 0x92, 0x69, 0xa7, 0xd3, 0x86, 0xf2, 0x4e, 0x9f, 0x6a, 0x90,
	0x5b, 0xc2, 0xf1, 0x77, 0x30, 0xd0, 0x0a, 0x98, 0x96, 0x30, 0x82, 0x5e, 0xea, 0xaf, 0x89, 0xc7,
	0xe8, 0x5b, 0x55, 0xd2, 0x23, 0xd7, 0x12, 0x81, 0x25, 0x7d, 0x4b, 0xd0, 0x29, 0x80, 0x3c, 0xe4,
	0xc9, 0x6b, 0x12, 0xcb, 0xbb, 0x4c, 0x57, 0xc2, 0x5f, 0x88, 0x00, 0x9e, 0xc3, 0x49, 0xc1, 0x56,
	0x16, 0xf5, 0x1c, 0x8e, 0xe4, 0xed, 0x43, 0x63, 0x6c, 0x4e, 0xec, 0xd9, 0xdd, 0xbd, 0xca, 0x5c,
	0x85, 0xc3, 0xcf, 0x25, 0x89, 0x6a, 0xcd, 0x7f, 0x21, 0xea, 0x5b, 0x40, 0x15, 0x5f, 0x29, 0xeb,
	0x0b, 0xe8, 0xaa, 0x3e, 0x14, 0xc2, 0x46, 0x8d, 0xc2, 0xf4, 0x84, 0x14, 0x58, 0xfc, 0x19, 0x74,
	0x54, 0x08, 0x0d, 0xa0, 0xa5, 0xbb, 0x64, 0xba, 0x2d, 0x1a, 0x96, 0xdd, 0x6f, 0x55, 0xdd, 0xc7,
	0x7f, 0x19, 0xd0, 0x9b, 0xe7, 0xc5, 0x9c, 0x5e, 0xc0, 0x80, 0x27, 0x1e, 0x4b, 0xfd, 0x80, 0x30,
	0xaf, 0x9c, 0x58, 0x7b, 0xf6, 0xe1, 0x4e, 0x8f, 0x97, 0x3c, 0xa3, 0xf1, 0x5a, 0x35, 0xb9, 0xcf,
	0x93, 0xa5, 0x4c, 0x79, 0x2e, 0xe6, 0xe9, 0x4e, 0x35, 0x20, 0xea, 0xa1, 0x4d, 0x33, 0x60, 0xfe,
	0xab, 0x19, 0x40, 0x8f, 0xa1, 0x5f, 0xe9, 0xd2, 0x63, 0x7a, 0x60, 0xf2, 0xa0, 0x10, 0xb5, 0x08,
	0xf1, 0x0f, 0x60, 0xcf, 0xf3, 0x6a, 0x89, 0x3e, 0x86, 0xf7, 0x62, 0x72, 0xe3, 0xe9, 0xa9, 0xaf,
	0x2d, 0xe6, 0x71, 0x4c, 0x6e, 0x54, 0xed, 0xe4, 0x4b, 0x30, 0x1c, 0xd7, 0x70, 0xe5, 0x7b, 0xec,
	0x12, 0xb5, 0x08, 0xf1, 0x2b, 0x80, 0x57, 0x34, 0x2d, 0x96, 0xe3, 0x3e, 0xd8, 0xbb, 0xac, 0xb0,
	0xaa, 0x28, 0x27, 0x70, 0x42, 0x99, 0x17, 0x92, 0x88, 0x70, 0xa2, 0xdf, 0x23, 0x59, 0x2d, 0x77,
	0x40, 0xd9, 0xa5, 0x0c, 0x2b, 0xd5, 0xf8, 0x11, 0xa0, 0x8a, 0xb8, 0x94, 0x7e, 0x06, 0xc7, 0x2a,
	0x39, 0xf4, 0x82, 0x24, 0xd7, 0x26, 0x60, 0xba, 0x7d, 0x1d, 0x9c, 0x8b, 0x18, 0xfe, 0xc3, 0x80,
	0xbe, 0xe2, 0xfa, 0x9f, 0x76, 0x56, 0x58, 0x11, 0x65, 0x5e, 0x4a, 0xb2, 0x8d, 0x1f, 0x93, 0x98,
	0xcb, 0x76, 0x5b, 0xae, 0x4d, 0xd9, 0x55, 0x11, 0xc2, 0x27, 0x30, 0x50, 0x1a, 0x8b, 0xb7, 0xe1,
	0xdf, 0x0d, 0xb0, 0x0a, 0xae, 0x46, 0xc7, 0xfc, 0xaa, 0xee, 0x54, 0xad, 0xc3, 0x0f, 0x29, 0x6d,
	0x0c, 0x3d, 0xde, 0xee, 0x8b, 0xf9, 0x0f, 0x86, 0xba, 0xd6, 0x35, 0xfc, 0x5b, 0x0b, 0xda, 0x42,
	0xd9, 0xce, 0x46, 0x39, 0xef, 0x94, 0xa8, 0x57, 0xab, 0xc1, 0x29, 0x40, 0x20, 0x2d, 0x3c, 0xf4,
	0x7c, 0xae, 0x1d, 0xb7, 0xa7, 0x23, 0x4f, 0xb8, 0x38, 0xce, 0xd3, 0xb0, 0x38, 0x6e, 0xab, 0x63,
	0x1d, 0x79, 0xc2, 0x85, 0x9d, 0x6c, 0xe8, 0x86, 0x78, 0xfc, 0x4d, 0x4a, 0x86, 0x47, 0x8a, 0x5a,
	0x04, 0x5e, 0xbc, 0x49, 0xa5, 0x65, 0xcb, 0x7e, 0x4a, 0xaf, 0xe9, 0x28, 0xcb, 0x16, 0x01, 0xe9,
	0x35, 0x77, 0xa0, 0x9b, 0x33, 0x92, 0x89, 0x1a, 0x75, 0xd5, 0xfe, 0x89, 0xcf, 0x45, 0x88, 0xee,
	0x82, 0x25, 0x66, 0x2f, 0xf3, 0xaf, 0xf9, 0xd0, 0x92, 0x0d, 0xe9, 0x52, 0x76, 0x29, 0x3e, 0x05,
	0x61, 0xb5, 0x5c, 0x3d, 0x45, 0xc8, 0xf4, 0xf6, 0x88, 0x3c, 0x79, 0x5b, 0x9e, 0x45, 0x43, 0x90,
	0x4a, 0xe4, 0x34, 0x7d, 0x9f, 0x45, 0xb3, 0x3f, 0xdb, 0xd0, 0x97, 0x5e, 0xba, 0x24, 0xd9, 0xcf,
	0x34, 0x20, 0xe8, 0x1b, 0xe8, 0x6a, 0x7b, 0x45, 0xb8, 0x71, 0x58, 0xb6, 0xfe, 0x99, 0x38, 0xfb,
	0xad, 0x16, 0xbd, 0x04, 0xab, 0x30, 0x6a, 0x74, 0x76, 0x1b, 0x95, 0x36, 0x60, 0xe7, 0xa3, 0x5b,
	0x41, 0xe5, 0x06, 0xfd, 0x04, 0x50, 0x79, 0x2d, 0xda, 0x9b, 0xb4, 0x65, 0xee, 0xce, 0x27, 0x07,
	0x60, 0x25, 0xfb, 0x33, 0x30, 0xe7, 0x39, 0x47, 0xf7, 0x1a, 0xf1, 0xa5, 0xcf, 0x3a, 0xe3, 0x7d,
	0xe7, 0x25, 0xd1, 0x15, 0x74, 0xd4, 0x7a, 0xa0, 0x07, 0x8d, 0xd8, 0xfa, 0x7e, 0x3b, 0x67, 0xb7,
	0x40, 0x6a, 0x8c, 0x6d, 0x61, 0x28, 0xe8, 0x7e, 0x23, 0xb8, 0xf2, 0x9a, 0x3d, 0x8f, 0x6d, 0x30,
	0xa3, 0x15, 0xf4, 0xeb, 0x3f, 0x52, 0x50, 0x73, 0xe2, 0xee, 0xcf, 0x21, 0xe7, 0xd3, 0x83, 0xc0,
	0xe2, 0x8e, 0x0b, 0xf8, 0x51, 0x0e, 0x1f, 0xcb, 0xd2, 0x60, 0xd5, 0x91, 0x8b, 0xfa, 0xf9, 0xdf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x54, 0xa4, 0xd2, 0xe6, 0xa6, 0x09, 0x00, 0x00,
}
