// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Bucket is the predicate function for bucket builders.
type Bucket func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)
