// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// DoBuckets is the predicate function for dobuckets builders.
type DoBuckets func(*sql.Selector)
